# Generated by Django 4.2.1 on 2023-06-01 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0003_alter_todo_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="created_at",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="todo",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
