# Generated by Django 4.2.1 on 2023-06-01 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0004_alter_todo_created_at_alter_todo_due_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="todos", to="todo.tag"
            ),
        ),
    ]
